openapi: 3.0.3
info:
  title: TKT Berlin API
  version: 0.0.2
  description: API-Dokumentation zum DataHub des Tourismusvereins Berlin Treptow-Köpenick e.V.
paths:
  /items/event_occurrences:
    get:
      summary: Liste aller Termine eines Events
      description: Enhält alle Einzeltermine der Events sowie Informationen zu Status (active, postponed, cancelled). Termine werden automatisch aus der Wiederholungslogik eines Events generiert, können aber manuell überschrieben werden (updated_by_user = true).
      tags:
      - event_occurrences
      parameters:
      - name: filter[event][_eq]
        in: query
        description: ID des verknüpften Events (optional)
        required: false
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Gefilterte Liste von event_occurrences
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event_occurrences'
  /items/events?fields=*.*:
    get:
      summary: Liste aller items in events (Hauptevents)
      tags:
      - events
      responses:
        '200':
          description: A list of events items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'
  /items/events/{id}:
    get:
      summary: Ein einzelnes Event anhand der ID abrufen
      tags:
      - events
      parameters:
      - name: id
        in: path
        required: true
        description: ID des Events
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Ein einzelnes Event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/events'
  /items/organizations?fields=*.*:
    get:
      summary: List all items in organizations
      tags:
      - organizations
      responses:
        '200':
          description: A list of organizations items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organizations'
  /items/places?fields=*.*:
    get:
      summary: List all items in places
      tags:
      - places
      responses:
        '200':
          description: A list of places items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/places'
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    event_occurrences:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
        event:
          type: string
          format: uuid
        start_date:
          type: string
        end_date:
          type: string
        door_time:
          type: string
        updated_by_user:
          type: boolean
        original_date:
          type: string
        new_date:
          type: string
    events:
      type: object
      properties:
        id:
          type: string
          format: uuid
        sort:
          type: integer
        user_created:
          type: string
          format: uuid
        date_created:
          type: string
          format: date-time
        user_updated:
          type: string
          format: uuid
        date_updated:
          type: string
          format: date-time
        organization:
          $ref: '#/components/schemas/organizations'
        translations:
          $ref: '#/components/schemas/events_translations'
        type:
          type: string
          description: Unterscheidung nach event, programm, führung
        categories:
          type: string
        start_date:
          type: dateTime
          description: Initiales Startdatum. Wird vor allem für die Wiederholungslogik verwendet und entsprechend immer für die Generierung des ersten Termins verwendet
        end_date:
          type: dateTime
          description: Initiales Endatum. Wird vor allem für die Wiederholungslogik verwendet und entsprechend immer für die Generierung des ersten Termins verwendet
        ticket_link:
          type: string
          description: URL zu einem Ticketsystem im Format https://...
        featured_image:
          type: string
          format: uuid
          description: BildURLs sind nach folgendem Schema aufgebaut - https://data.tkt-berlin.de/assets/[id]
        external_link:
          type: string
          description: URL zu einer passenden Eventwebseite im Format https://...
        is_highlight:
          type: boolean
          description: Gibt an ob eine Veranstaltung hervorgehoben werden soll.
        gallery:
          type: array
          description: BildURLs sind nach folgendem Schema aufgebaut - https://data.tkt-berlin.de/assets/[id]
        is_recurring:
          type: boolean
          description: Gibt an, ob eine Wiederholungslogik greift oder nicht. Der erste Termin wird allerdings immer generiert, auch wenn is_recurring = false
        price:
          type: number
          format: float
        location:
          $ref: '#/components/schemas/places'
        group_size_min:
          type: integer
          description: Nur bei type = programm
        group_size_max:
          type: integer
        door_time:
          type: string
        event_time:
          type: string
        repeat_frequency:
          type: string
        by_day:
          type: string
        by_month:
          type: string
        repeat_count:
          type: integer
        except_dates:
          type: string
        occurrences:
          type: string
        by_month_week:
          type: string
        by_month_day:
          type: string
        archived:
          type: boolean
        monthly_recurring_type:
          type: string
        layout_wrapper:
          type: string
        sidebar:
          type: string
        content_wrapper:
          type: string
        details:
          type: string
    events_translations:
      type: object
      properties:
        id:
          type: integer
        events_id:
          type: string
          format: uuid
        languages_code:
          type: string
        title:
          type: string
        slug:
          type: string
        description:
          type: string
        short_description:
          type: string
        tags:
          type: string
        is_active:
          type: boolean
        duration:
          type: string
        ticket_info:
          type: string
        languages:
          type: string
    organizations:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_created:
          type: string
          format: uuid
        date_created:
          type: string
          format: date-time
        user_updated:
          type: string
          format: uuid
        date_updated:
          type: string
          format: date-time
        translations:
          type: string
        name:
          type: string
        type:
          type: string
          format: uuid
        phone:
          type: string
        email:
          type: string
        website:
          type: string
        address:
          type: string
        postal_code:
          type: string
        city:
          type: string
        logo:
          type: string
          format: uuid
        featured_image:
          type: string
          format: uuid
        jobs:
          type: string
        persons:
          type: string
        places:
          type: string
        events:
          type: string
        not_berlin:
          type: boolean
        address_data:
          type: string
        layout_wrapper:
          type: string
        sidebar:
          type: string
        content_wrapper:
          type: string
        connections:
          type: string
    organizations_translations:
      type: object
      properties:
        id:
          type: integer
        organizations_id:
          type: string
          format: uuid
        languages_code:
          type: string
        short_description:
          type: string
    places:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_created:
          type: string
          format: uuid
        date_created:
          type: string
          format: date-time
        user_updated:
          type: string
          format: uuid
        date_updated:
          type: string
          format: date-time
        lat:
          type: string
        long:
          type: string
        place_id:
          type: string
        rating:
          type: string
        status:
          type: string
        featured_image:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        city:
          type: string
        phone:
          type: string
        email:
          type: string
        weblink:
          type: string
        address:
          type: string
        postal_code:
          type: string
        organization:
          type: string
        translations:
          type: string
        jobs:
          type: string
        layout_wrapper:
          type: string
        sidebar:
          type: string
        content_wrapper:
          type: string
        address_data:
          type: string
        opening_data:
          type: string
        opening_hours:
          type: string
        content_data:
          type: string
        categories:
          type: string
        routes:
          type: string
        events:
          type: string
        connections:
          type: string
        is_not_berlin:
          type: boolean
    places_translations:
      type: object
      properties:
        id:
          type: integer
        places_id:
          type: string
          format: uuid
        languages_code:
          type: string
        active:
          type: boolean
        name:
          type: string
        short_description:
          type: string
        content:
          type: string
servers:
- url: https://data.tkt-berlin.de
  description: DataHub von TKT Berlin
